Feature/UI performance
sitcomlab/simport-learning-app pull request #104
Opened 2021-09-08 13:57 UTC by schrooom

2021-09-08 14:00 UTC, schrooom commented
WIP: fixing the tests…

2021-10-04 07:46 UTC, felixerdy approved these changes

2021-10-04 07:49 UTC, felixerdy requested changes
@schrooom can you resolve the occuring conflicts in `src/app/shared-services/inferences/inference.service.ts` before we can merge this PR?

2021-10-04 10:17 UTC, schrooom commented
> @schrooom can you resolve the occuring conflicts in `src/app/shared-services/inferences/inference.service.ts` before we can merge this PR?

Thanks for the heads-up – conflicts are resolved :)

2021-10-04 11:06 UTC, merged