#219: adjust file-write directory for Android 10 and above + refactor
sitcomlab/simport-learning-app pull request #221
Opened 2022-07-27 13:10 UTC by schrooom

Closes #219

2022-08-04 13:05 UTC, felixerdy approved these changes
Looks good to me 👍

2022-08-04 13:07 UTC, felixerdy requested changes
There are some issues in the automatic tests. Can you check on them?

2022-08-04 14:02 UTC, schrooom commented
Thanks for the heads-up – didn't notice that. Tests are fixed 👍🏻

2022-08-05 08:03 UTC, felixerdy approved these changes

2022-08-05 08:03 UTC, merged